### ISSUE TITLE
Optional outbound config file

### ISSUE THREAD

**Issue by panstav** [nozzle/nzAnimate#10]
I use heroku for hosting, which means that node modules & bower components stay out of the deployment pack. 

Correct me if I'm wrong but.. Having the nzAnimate config file **inside** of the bower component means I have no control over the build process, right?

**Comment by tannerlinsley** [comment]
@panstav I'm not too familiar with heroku, but if you simply install the bower/node module and use it out of the box in an environment you can't manipulate, then yes, you can't do a custom build.  The custom build functionality is more meant to be done locally and deployed remotely.  

In almost all cases, the custom build process would only have to be once locally and then the resulting `nzAnimate.min.css` file can be placed anywhere.  

If you wanted a dynamic build that could change on a whim (I can't imagine a use case though), you would have to have a remote node box somewhere that could produce a new build for you using a config there.  I hope this helps.

**Comment by panstav** [comment]
Thanks for the quick reply, I would go by your first suggestion.
