### ISSUE TITLE
Not working on ngHide

### ISSUE THREAD

**Issue by nitrium** [nozzle/nzAnimate#4]
Before I do a PR, wanted to know if you're aware that currently nzAnimate doesn't work on ngHide (ng-hide-add, ng-hide-remove).

**Comment by tannerlinsley** [comment]
@nitrium Well shoot, I totally spaced it!  Let's get that added in. I can go ahead and do it, or if you have a PR, let's get it in there!

**Comment by tannerlinsley** [comment]
@nitrium I'm going to hurry and throw it together.  If you have something, let me know asap.

**Comment by nitrium** [comment]
I won't be able to put something together until tomorrow, so go ahead. But after you do that, I have a suggestion for passing X and Y values to the animations :-)

**Comment by tannerlinsley** [comment]
@nitrium I added ng-show & ng-hide functionality.  Remember it does require the animate class if no speed class is defined.  If you have or find errors, please reopen :)
